-- Creacion tablas
CREATE TABLE bodega (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL,
    tamano NUMBER(5, 0) NOT NULL,
    sucursal_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE bodega ADD CONSTRAINT bodega_pk PRIMARY KEY ( id );

CREATE TABLE bodegaproducto (
    existencias NUMBER(10, 0) NOT NULL,
    preciopromedio NUMBER(10, 2) NOT NULL,
    capacidad NUMBER(10, 0) NOT NULL,
    bodega_id NUMBER(10, 0) NOT NULL,
    producto_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE bodegaproducto ADD CONSTRAINT bodegaproducto_pk PRIMARY KEY ( bodega_id, producto_id );

CREATE TABLE categoria (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL,
    descripcion VARCHAR2(510) NOT NULL,
    caracteristicas VARCHAR2(510) NOT NULL
);

ALTER TABLE categoria ADD CONSTRAINT categoria_pk PRIMARY KEY ( id );

CREATE TABLE ciudad (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL
);

ALTER TABLE ciudad ADD CONSTRAINT ciudad_pk PRIMARY KEY ( id );

CREATE TABLE ordencompra (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    fechacreacion DATE NOT NULL,
    fechaentrega DATE NOT NULL,
    fecharecepcion DATE,
    estado VARCHAR2(50) NOT NULL,
    proveedor_id NUMBER(10, 0) NOT NULL,
    sucursal_id NUMBER(10, 0) NOT NULL,
    bodega_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE ordencompra ADD CONSTRAINT ordencompra_pk PRIMARY KEY ( id );

CREATE TABLE ordenproducto (
    cantidad NUMBER(10, 0) NOT NULL,
    precio NUMBER(10, 2) NOT NULL,
    ordencompra_id NUMBER(10, 0) NOT NULL,
    producto_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE ordenproducto ADD CONSTRAINT ordenproducto_pk PRIMARY KEY ( ordencompra_id, producto_id );

CREATE TABLE producto (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL,
    costobodega NUMBER(10, 2) NOT NULL,
    preciounitario NUMBER(10, 2) NOT NULL,
    presentacion VARCHAR2(255) NOT NULL,
    cantidad NUMBER(10, 0) NOT NULL,
    unidadmedida VARCHAR2(50) NOT NULL,
    volumenempaque NUMBER(10, 2) NOT NULL,
    pesoempaque NUMBER(10, 2) NOT NULL,
    fechaexpiracion DATE,
    codigobarras VARCHAR2(50) NOT NULL,
    categoria_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE producto ADD CONSTRAINT producto_pk PRIMARY KEY ( id );

CREATE TABLE productosucursal (
    cantidadminima NUMBER(10, 0) NOT NULL,
    sucursal_id NUMBER(10, 0) NOT NULL,
    producto_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE productosucursal ADD CONSTRAINT productosucursal_pk PRIMARY KEY ( sucursal_id, producto_id );

CREATE TABLE proveedor (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nit NUMBER(10, 0) NOT NULL,
    nombre VARCHAR2(255) NOT NULL,
    direccion VARCHAR2(255) NOT NULL,
    nombrecontacto VARCHAR2(255) NOT NULL,
    telefonocontacto NUMBER(15, 0) NOT NULL
);

ALTER TABLE proveedor ADD CONSTRAINT proveedor_pk PRIMARY KEY ( id );

CREATE TABLE proveedorproducto (
    producto_id NUMBER(10, 0) NOT NULL,
    proveedor_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE proveedorproducto ADD CONSTRAINT proveedorproducto_pk PRIMARY KEY ( producto_id, proveedor_id );

CREATE TABLE proveedorsucursal (
    sucursal_id NUMBER(10, 0) NOT NULL,
    proveedor_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE proveedorsucursal ADD CONSTRAINT proveedorsucursal_pk PRIMARY KEY ( sucursal_id, proveedor_id );

CREATE TABLE sucursal (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL,
    direccion VARCHAR2(255) NOT NULL,
    telefono NUMBER(15, 0) NOT NULL,
    tamano NUMBER(5, 0) NOT NULL,
    ciudad_id NUMBER(10, 0) NOT NULL
);

ALTER TABLE sucursal ADD CONSTRAINT sucursal_pk PRIMARY KEY ( id );

-- Relacionando las tablas
ALTER TABLE bodega ADD CONSTRAINT bodega_sucursal_fk FOREIGN KEY ( sucursal_id ) REFERENCES sucursal ( id );
ALTER TABLE bodegaproducto ADD CONSTRAINT bodegaproducto_bodega_fk FOREIGN KEY ( bodega_id ) REFERENCES bodega ( id );
ALTER TABLE bodegaproducto ADD CONSTRAINT bodegaproducto_producto_fk FOREIGN KEY ( producto_id ) REFERENCES producto ( id );
ALTER TABLE ordencompra ADD CONSTRAINT ordencompra_bodega_fk FOREIGN KEY ( bodega_id ) REFERENCES bodega ( id );
ALTER TABLE ordencompra ADD CONSTRAINT ordencompra_proveedor_fk FOREIGN KEY ( proveedor_id ) REFERENCES proveedor ( id );
ALTER TABLE ordencompra ADD CONSTRAINT ordencompra_sucursal_fk FOREIGN KEY ( sucursal_id ) REFERENCES sucursal ( id );
ALTER TABLE ordenproducto ADD CONSTRAINT ordenproducto_ordencompra_fk FOREIGN KEY ( ordencompra_id ) REFERENCES ordencompra ( id );
ALTER TABLE ordenproducto ADD CONSTRAINT ordenproducto_producto_fk FOREIGN KEY ( producto_id ) REFERENCES producto ( id );
ALTER TABLE producto ADD CONSTRAINT producto_categoria_fk FOREIGN KEY ( categoria_id ) REFERENCES categoria ( id );
ALTER TABLE productosucursal ADD CONSTRAINT productosucursal_producto_fk FOREIGN KEY ( producto_id ) REFERENCES producto ( id );
ALTER TABLE productosucursal ADD CONSTRAINT productosucursal_sucursal_fk FOREIGN KEY ( sucursal_id ) REFERENCES sucursal ( id );
ALTER TABLE proveedorproducto ADD CONSTRAINT proveedorproducto_producto_fk FOREIGN KEY ( producto_id ) REFERENCES producto ( id );
ALTER TABLE proveedorproducto ADD CONSTRAINT proveedorproducto_proveedor_fk FOREIGN KEY ( proveedor_id ) REFERENCES proveedor ( id );
ALTER TABLE proveedorsucursal ADD CONSTRAINT proveedorsucursal_proveedor_fk FOREIGN KEY ( proveedor_id ) REFERENCES proveedor ( id );
ALTER TABLE proveedorsucursal ADD CONSTRAINT proveedorsucursal_sucursal_fk FOREIGN KEY ( sucursal_id ) REFERENCES sucursal ( id );
ALTER TABLE sucursal ADD CONSTRAINT sucursal_ciudad_fk FOREIGN KEY ( ciudad_id ) REFERENCES ciudad ( id );

-- Poblacion de tabla categoria
INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Perecederos', 'Perecederos, tienen fecha de vencimiento', 'Almacenamiento en fr�o, con fecha de caducidad');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('No perecederos', 'No perecederos, sin fecha de vencimiento cercana', 'Almacenamiento en lugar seco y fresco');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Aseo', 'Productos de limpieza y aseo', 'Almacenamiento en lugares ventilados y seguros');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Congelados', 'Alimentos y productos congelados', 'Almacenamiento en congeladores a temperaturas bajo cero');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Prendas de vestir', 'Ropa y prendas de uso personal', 'Almacenamiento en estantes y perchas');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Muebles', 'Mobiliario para el hogar u oficina', 'Almacenamiento en lugares amplios, evitar humedad');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Herramientas', 'Herramientas de trabajo y uso dom�stico', 'Almacenamiento en cajas de herramientas, lugares secos');

INSERT INTO categoria (nombre, descripcion, caracteristicas)
VALUES ('Electrodom�sticos', 'Aparatos el�ctricos para uso dom�stico', 'Almacenamiento en lugares seguros, evitar golpes');

-- Poblacion de tabla productos
-- Poblaci�n tabla producto de productos perecederos
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Papas fritas Les frites', 4200, 9000, 'Paquet�n de 5 paquetes de 200 gr.', 1000, 'gr', 150, 15, TO_DATE('12/12/2027', 'DD/MM/YYYY'), 'f0f0f0f0f0', 1);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Leche Deslactosada Alpina', 2000, 3000, 'Caja de 6 botellas de 1 litro', 6000, 'ml', 1000, 50, TO_DATE('01/01/2025', 'DD/MM/YYYY'), 'a1a1a1a1a1', 1);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Queso Mozzarella La Quesera', 8500, 15000, 'Bloque de 500 gr.', 500, 'gr', 200, 30, TO_DATE('30/09/2026', 'DD/MM/YYYY'), 'b2b2b2b2b2', 1);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Yogurt Natural Alpina', 1800, 2500, 'Paquete de 6 botellas de 250 ml', 1500, 'ml', 120, 20, TO_DATE('15/06/2026', 'DD/MM/YYYY'), 'c3c3c3c3c3', 1);

-- Poblaci�n tabla producto de productos no perecederos
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('At�n en lata Van Camps', 3000, 5500, 'Caja de 6 latas de 150 gr.', 900, 'gr', 100, 25, NULL, 'd4d4d4d4d4', 2);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Frijoles enlatados La Roca', 1500, 3000, 'Lata de 500 gr.', 500, 'gr', 120, 40, NULL, 'e5e5e5e5e5', 2);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Arroz Blanco Diana', 800, 1600, 'Bolsa de 1 Kg.', 1000, 'gr', 200, 20, NULL, 'f6f6f6f6f6', 2);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Galletas Salt�n Noel', 2200, 4000, 'Paquete de 12 galletas', 500, 'gr', 150, 10, NULL, 'g7g7g7g7g7', 2);

-- Poblaci�n tabla producto de productos de aseo
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Detergente en polvo Ariel', 5000, 10000, 'Bolsa de 2 Kg.', 2000, 'gr', 500, 50, NULL, 'h8h8h8h8h8', 3);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Jab�n L�quido Protex', 1200, 2400, 'Botella de 500 ml.', 500, 'ml', 100, 20, NULL, 'i9i9i9i9i9', 3);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Desinfectante Lysol', 6000, 12000, 'Spray de 1 litro', 1000, 'ml', 200, 60, NULL, 'j0j0j0j0j0', 3);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Cloro Blanquita', 800, 1600, 'Botella de 2 litros', 2000, 'ml', 300, 100, NULL, 'k1k1k1k1k1', 3);

-- Poblaci�n tabla producto de productos congelados
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Helado de Vainilla Popsy', 5000, 9000, 'Caja de 1 litro', 1000, 'ml', 300, 500, NULL, 'l2l2l2l2l2', 4);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Nuggets de Pollo McCain', 7000, 14000, 'Paquete de 1 Kg.', 1000, 'gr', 400, 600, NULL, 'm3m3m3m3m3', 4);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Pizza Congelada Ristorante', 4500, 9000, 'Paquete de 500 gr.', 500, 'gr', 200, 150, NULL, 'n4n4n4n4n4', 4);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Papas Fritas McCain', 3500, 7000, 'Paquete de 1 Kg.', 1000, 'gr', 300, 250, NULL, 'o5o5o5o5o5', 4);

-- Poblaci�n tabla producto de prendas de vestir
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Camisa de Algod�n', 10000, 25000, 'Paquete de 1 unidad', 500, 'gr', 200, 100, NULL, 'p6p6p6p6p6', 5);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Pantal�n Jeans', 15000, 40000, 'Paquete de 1 unidad', 700, 'gr', 300, 200, NULL, 'q7q7q7q7q7', 5);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Camiseta Deportiva', 5000, 15000, 'Paquete de 1 unidad', 300, 'gr', 100, 80, NULL, 'r8r8r8r8r8', 5);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Chaqueta de Cuero', 30000, 60000, 'Paquete de 1 unidad', 1200, 'gr', 500, 300, NULL, 's9s9s9s9s9', 5);

-- Poblaci�n tabla producto de muebles
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Silla de Oficina', 50000, 100000, 'Paquete de 1 unidad', 10000, 'gr', 5000, 3000, NULL, 't1t1t1t1t1', 6);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Mesa de Centro', 70000, 150000, 'Paquete de 1 unidad', 15000, 'gr', 8000, 4000, NULL, 'u2u2u2u2u2', 6);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Sof� de 3 Plazas', 120000, 300000, 'Paquete de 1 unidad', 40000, 'gr', 20000, 10000, NULL, 'v3v3v3v3v3', 6);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Estante de Madera', 40000, 80000, 'Paquete de 1 unidad', 25000, 'gr', 15000, 6000, NULL, 'w4w4w4w4w4', 6);

-- Poblaci�n tabla producto de herramientas
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Martillo', 5000, 10000, 'Paquete de 1 unidad', 500, 'gr', 300, 200, NULL, 'x5x5x5x5x5', 7);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Destornillador', 3000, 8000, 'Paquete de 1 unidad', 200, 'gr', 100, 80, NULL, 'y6y6y6y6y6', 7);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Llave Inglesa', 8000, 15000, 'Paquete de 1 unidad', 700, 'gr', 400, 300, NULL, 'z7z7z7z7z7', 7);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Taladro El�ctrico', 25000, 50000, 'Paquete de 1 unidad', 2000, 'gr', 1500, 1200, NULL, 'a8a8a8a8a8', 7);

-- Poblaci�n tabla producto de electrodom�sticos
INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Televisor 42 pulgadas', 300000, 600000, 'Paquete de 1 unidad', 20000, 'gr', 5000, 3000, NULL, 'b9b9b9b9b9', 8);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Nevera No Frost', 500000, 1000000, 'Paquete de 1 unidad', 40000, 'gr', 10000, 6000, NULL, 'c0c0c0c0c0', 8);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Microondas', 80000, 150000, 'Paquete de 1 unidad', 10000, 'gr', 3000, 1500, NULL, 'd1d1d1d1d1', 8);

INSERT INTO producto (nombre, costobodega, preciounitario, presentacion, cantidad, unidadmedida, volumenempaque, pesoempaque, fechaexpiracion, codigobarras, categoria_id)
VALUES ('Aspiradora', 90000, 180000, 'Paquete de 1 unidad', 15000, 'gr', 4000, 2500, NULL, 'e2e2e2e2e2', 8);

-- Poblaci�n tabla ciudad
INSERT INTO ciudad (nombre) 
VALUES ('Bucaramanga');

INSERT INTO ciudad (nombre) 
VALUES ('Bogot�');

-- Poblaci�n tabla sucursal en Bucaramanga
INSERT INTO sucursal (nombre, direccion, telefono, tamano, ciudad_id) 
VALUES ('Sucursal Norte', 'Calle 1 #2-3', 1234567, 1200, (SELECT id FROM ciudad WHERE nombre = 'Bucaramanga'));

INSERT INTO sucursal (nombre, direccion, telefono, tamano, ciudad_id) 
VALUES ('Sucursal Sur', 'Calle 4 #5-6', 7654321, 800, (SELECT id FROM ciudad WHERE nombre = 'Bucaramanga'));

-- Poblacion tabla sucursal
-- Poblaci�n tabla sucursal en Bogot�
INSERT INTO sucursal (nombre, direccion, telefono, tamano, ciudad_id) 
VALUES ('Sucursal Occidente', 'Carrera 7 #8-9', 1112222, 1500, (SELECT id FROM ciudad WHERE nombre = 'Bogot�'));

INSERT INTO sucursal (nombre, direccion, telefono, tamano, ciudad_id) 
VALUES ('Sucursal Oriente', 'Carrera 10 #11-12', 3334444, 1000, (SELECT id FROM ciudad WHERE nombre = 'Bogot�'));

-- Poblacion tabla bodega
-- Poblaci�n tabla bodega para las sucursales de Bucaramanga
INSERT INTO bodega (nombre, tamano, sucursal_id)
VALUES ('Bodega Cabecera del Llano', 500, (SELECT id FROM sucursal WHERE nombre = 'Sucursal Norte'));

INSERT INTO bodega (nombre, tamano, sucursal_id)
VALUES ('Bodega Real de Minas', 300, (SELECT id FROM sucursal WHERE nombre = 'Sucursal Sur'));

-- Poblaci�n tabla bodega para las sucursales de Bogot�
INSERT INTO bodega (nombre, tamano, sucursal_id)
VALUES ('Bodega Portal 80', 700, (SELECT id FROM sucursal WHERE nombre = 'Sucursal Occidente'));

INSERT INTO bodega (nombre, tamano, sucursal_id)
VALUES ('Bodega Usme', 450, (SELECT id FROM sucursal WHERE nombre = 'Sucursal Oriente'));

-- Poblaci�n tabla proveedor
INSERT INTO proveedor (nit, nombre, direccion, nombrecontacto, telefonocontacto)
VALUES (9001234567, 'Proveedor de Alimentos S.A.', 'Carrera 15 #45-67, Bogot�', 'Carlos Ram�rez', 3111234567);

INSERT INTO proveedor (nit, nombre, direccion, nombrecontacto, telefonocontacto)
VALUES (9007654321, 'Distribuidora de Aseo Ltda.', 'Avenida 68 #22-55, Bogot�', 'Laura G�mez', 3207654321);

INSERT INTO proveedor (nit, nombre, direccion, nombrecontacto, telefonocontacto)
VALUES (9004567890, 'Comercializadora Congelados S.A.S.', 'Calle 100 #15-75, Bogot�', 'Juan P�rez', 3004567890);

INSERT INTO proveedor (nit, nombre, direccion, nombrecontacto, telefonocontacto)
VALUES (9009876543, 'Muebles y Estilos S.A.S', 'Calle 80 #20-30, Bogot�', 'Sandra Rodr�guez', 3109876543);

INSERT INTO proveedor (nit, nombre, direccion, nombrecontacto, telefonocontacto)
VALUES (9006543210, 'Electrodom�sticos del Hogar Ltda.', 'Carrera 30 #75-10, Bogot�', 'Jorge Mart�nez', 3016543210);

INSERT INTO proveedor (id, nit, nombre, direccion, nombrecontacto, telefonocontacto)
VALUES (6, 1234567890, 'Proveedor de Ropa S.A.', 'Carrera 10 #20-30, Bogot�', 'Ana Mar�a L�pez', 3201234567);

-- Poblacion proveedorproducto
-- Poblaci�n tabla proveedorproducto para Proveedor de Alimentos S.A.
INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Papas fritas Les frites'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Leche Deslactosada Alpina'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Queso Mozzarella La Quesera'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Yogurt Natural Alpina'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'At�n en lata Van Camps'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Frijoles enlatados La Roca'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Arroz Blanco Diana'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Galletas Salt�n Noel'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Alimentos S.A.'));

-- Poblaci�n tabla proveedorproducto para Comercializadora Congelados S.A.S.
INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Helado de Vainilla Popsy'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Nuggets de Pollo McCain'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Pizza Congelada Ristorante'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Papas Fritas McCain'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Queso Mozzarella La Quesera'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Yogurt Natural Alpina'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Leche Deslactosada Alpina'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Frijoles enlatados La Roca'), (SELECT id FROM proveedor WHERE nombre = 'Comercializadora Congelados S.A.S.'));

-- Poblaci�n tabla proveedorproducto para Distribuidora de Aseo Ltda.
INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Detergente en polvo Ariel'), (SELECT id FROM proveedor WHERE nombre = 'Distribuidora de Aseo Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Jab�n L�quido Protex'), (SELECT id FROM proveedor WHERE nombre = 'Distribuidora de Aseo Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Desinfectante Lysol'), (SELECT id FROM proveedor WHERE nombre = 'Distribuidora de Aseo Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Cloro Blanquita'), (SELECT id FROM proveedor WHERE nombre = 'Distribuidora de Aseo Ltda.'));

-- Poblaci�n tabla proveedorproducto para Proveedor de Ropa S.A.
INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Camisa de Algod�n'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Ropa S.A.S'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Pantal�n Jeans'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Ropa S.A.S'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Camiseta Deportiva'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Ropa S.A.S'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Chaqueta de Cuero'), (SELECT id FROM proveedor WHERE nombre = 'Proveedor de Ropa S.A.S'));

-- Poblaci�n tabla proveedorproducto para Muebles y Estilos S.A.
INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Silla de Oficina'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Mesa de Centro'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Sof� de 3 Plazas'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Estante de Madera'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Martillo'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Destornillador'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Llave Inglesa'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Taladro El�ctrico'), (SELECT id FROM proveedor WHERE nombre = 'Muebles y Estilos S.A.S'));

-- Poblaci�n tabla proveedorproducto para Electrodom�sticos del Hogar Ltda.
INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Televisor 42 pulgadas'), (SELECT id FROM proveedor WHERE nombre = 'Electrodom�sticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Nevera No Frost'), (SELECT id FROM proveedor WHERE nombre = 'Electrodom�sticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Microondas'), (SELECT id FROM proveedor WHERE nombre = 'Electrodom�sticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Aspiradora'), (SELECT id FROM proveedor WHERE nombre = 'Electrodom�sticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Silla de Oficina'), (SELECT id FROM proveedor WHERE nombre = 'Electrodom�sticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Mesa de Centro'), (SELECT id FROM proveedor WHERE nombre = 'Electrodom�sticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Sof� de 3 Plazas'), (SELECT id FROM proveedor WHERE nombre = 'Electrodom�sticos del Hogar Ltda.'));

INSERT INTO proveedorproducto (producto_id, proveedor_id)
VALUES ((SELECT id FROM producto WHERE nombre = 'Estante de Madera'), (SELECT id FROM proveedor WHERE nombre = 'Electrodom�sticos del Hogar Ltda.'));

COMMIT;