-- Insertando datos en la tabla 'hoteles'
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Oasis', 123456789, 1);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Marina Bay Sands', 987654321, 2);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('The Plaza', 555666777, 3);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Waldorf Astoria', 333222111, 4);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Beverly Hills Hotel', 444555666, 5);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Pacifico', 100000006, 6);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Atlantico', 100000007, 7);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Andino', 100000008, 8);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Caribe', 100000009, 9);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Amazonas', 100000010, 10);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Sierra', 100000011, 11);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Urbano', 100000012, 12);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Colonial', 100000013, 13);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Imperial', 100000014, 14);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Majestic', 100000015, 15);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Irotama', 100000016, 16);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Panorama', 100000017, 17);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Riviera', 100000018, 18);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Solaris', 100000019, 19);
INSERT INTO hoteles (nombrehotel, nithotel, idhotel) VALUES ('Hotel Cosmos', 100000020, 20);

-- Insertando datos en la tabla 'tipos'
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Doble', 2, '2 camas, baño privado, TV', 1);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Familiar', 4, '4 camas, 2 baños privados, TV, cocina', 2);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Sencilla', 1, '1 cama, baño privado, TV', 3);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Suite', 2, '1 cama grande, jacuzzi, baño privado, TV, sala de estar', 4);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Suite Presidencial', 2, '1 cama king, jacuzzi, baño privado, TV, sala de estar, vista al mar', 5);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Doble', 2, 'Cama doble, baño privado, TV', 6);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Familiar', 4, 'Dos camas dobles, baño privado, TV, sala de estar', 7);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Sencilla', 1, 'Cama sencilla, baño privado, TV', 8);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Suite', 2, 'Cama Queen, baño de lujo, minibar, TV', 9);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Suite Presidencial', 2, 'Cama King, jacuzzi, sala de estar, oficina, vista al mar', 10);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Doble', 2, 'Cama doble, baño privado, TV, vista al jardín', 11);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Familiar', 4, 'Dos camas dobles, baño privado, balcón, TV', 12);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Sencilla', 1, 'Cama sencilla, baño privado, ventana al patio', 13);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Suite', 2, 'Cama Queen, baño con tina, minibar, área de trabajo', 14);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Suite Presidencial', 2, 'Cama King, sala de estar amplia, comedor, terraza privada', 15);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Doble', 2, 'Dos camas individuales, baño privado, armario amplio', 16);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Familiar', 4, 'Cama doble y literas, baño privado, mesa de juegos', 17);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Sencilla', 1, 'Cama individual, baño con ducha, escritorio', 18);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Suite', 2, 'Cama matrimonial, baño con hidromasaje, sala de estar con sofá', 19);
INSERT INTO tipos (tipo, capacidad, dotacion, idtipo) VALUES ('Suite Presidencial', 2, 'Cama tamaño imperial, vestidor, baño de mármol, servicio de mayordomo', 20);

-- Insertando datos en la tabla 'planes'
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Larga_Estadia', 10.0, 1);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Promo_Particular', 15.0, 2);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Tiempo_Compartido', 5.0, 3);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Todo_Incluido', 20.0, 4);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Larga_Estadia', 8.0, 5);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Larga_Estadia', 10.0, 6);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Promo_Particular', 15.0, 7);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Tiempo_Compartido', 20.0, 8);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Todo_Incluido', 25.0, 9);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Larga_Estadia', 30.0, 10);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Promo_Particular', 12.0, 11);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Tiempo_Compartido', 18.0, 12);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Todo_Incluido', 22.0, 13);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Larga_Estadia', 35.0, 14);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Promo_Particular', 10.0, 15);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Tiempo_Compartido', 16.0, 16);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Todo_Incluido', 28.0, 17);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Larga_Estadia', 25.0, 18);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Promo_Particular', 15.0, 19);
INSERT INTO planes (tipoplan, descuento, idplan) VALUES ('Tiempo_Compartido', 30.0, 20);

-- Insertando datos en la tabla 'alojamientos'
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2023-01-01','YYYY-MM-DD'), TO_DATE('2023-01-10','YYYY-MM-DD'), 1, 1, 1);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('NO', TO_DATE('2023-02-15','YYYY-MM-DD'), TO_DATE('2023-02-20','YYYY-MM-DD'), 2, 2, 2);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2023-03-10','YYYY-MM-DD'), TO_DATE('2023-03-15','YYYY-MM-DD'), 3, 3, 3);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2023-04-05','YYYY-MM-DD'), TO_DATE('2023-04-12','YYYY-MM-DD'), 4, 4, 4);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('NO', TO_DATE('2023-05-01','YYYY-MM-DD'), TO_DATE('2023-05-08','YYYY-MM-DD'), 5, 5, 5);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2023-01-01','YYYY-MM-DD'), TO_DATE('2023-01-08','YYYY-MM-DD'), 6, 6, 6);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('NO', TO_DATE('2023-02-15','YYYY-MM-DD'), TO_DATE('2023-02-22','YYYY-MM-DD'), 7, 7, 7);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2023-03-10','YYYY-MM-DD'), TO_DATE('2023-03-17','YYYY-MM-DD'), 8, 8, 8);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2023-04-05','YYYY-MM-DD'), TO_DATE('2023-04-12','YYYY-MM-DD'), 9, 9, 9);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('NO', TO_DATE('2023-05-01','YYYY-MM-DD'), TO_DATE('2023-05-08','YYYY-MM-DD'), 10, 10, 10);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2023-06-15','YYYY-MM-DD'), TO_DATE('2023-06-22','YYYY-MM-DD'), 11, 11, 11);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2023-07-19','YYYY-MM-DD'), TO_DATE('2023-07-26','YYYY-MM-DD'), 12, 12, 12);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('NO', TO_DATE('2023-08-10','YYYY-MM-DD'), TO_DATE('2023-08-17','YYYY-MM-DD'), 13, 13, 13);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2023-09-05','YYYY-MM-DD'), TO_DATE('2023-09-12','YYYY-MM-DD'), 14, 14, 14);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2023-10-21','YYYY-MM-DD'), TO_DATE('2023-10-28','YYYY-MM-DD'), 15, 15, 15);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('NO', TO_DATE('2023-11-11','YYYY-MM-DD'), TO_DATE('2023-11-18','YYYY-MM-DD'), 16, 16, 16);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2023-12-01','YYYY-MM-DD'), TO_DATE('2023-12-08','YYYY-MM-DD'), 17, 17, 17);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2024-01-15','YYYY-MM-DD'), TO_DATE('2024-01-22','YYYY-MM-DD'), 18, 18, 18);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('NO', TO_DATE('2024-02-18','YYYY-MM-DD'), TO_DATE('2024-02-25','YYYY-MM-DD'), 19, 19, 19);
INSERT INTO alojamientos (activa, checkin, checkout, acompanantes, idplan, idalojamiento) VALUES ('SI', TO_DATE('2024-03-10','YYYY-MM-DD'), TO_DATE('2024-03-17','YYYY-MM-DD'), 20, 20, 20);

-- Insertando datos en la tabla 'usuarios'
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Ana Ramirez', 'CC', 1012345678, 'ana.ramirez@email.com', 1, 1);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Luis Morales', 'CE', 2012345679, 'luis.morales@email.com', 2, 2);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Sofia Cruz', 'TI', 3012345680, 'sofia.cruz@email.com', 3, 3);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Carlos Gómez', 'PASAPORTE', 4012345681, 'carlos.gomez@email.com', 4, 4);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('María Alzate', 'CC', 5012345682, 'maria.alzate@email.com', 5, 5);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Jorge Martínez', 'CC', 6012345683, 'jorge.martinez@email.com', 6, 6);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Lucía Hernández', 'NIT', 7012345684, 'lucia.hernandez@email.com', 7, 7);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('David Guerrero', 'CE', 8012345685, 'david.guerrero@email.com', 8, 8);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Daniela Jiménez', 'TI', 9012345686, 'daniela.jimenez@email.com', 9, 9);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Miguel Ángel Toro', 'PASAPORTE', 10012345687, 'miguel.toro@email.com', 10, 10);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Tatiana Ruiz', 'CC', 11012345688, 'tatiana.ruiz@email.com', 11, 11);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Santiago Navas', 'CE', 12012345689, 'santiago.navas@email.com', 12, 12);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Laura Torres', 'TI', 13012345690, 'laura.torres@email.com', 13, 13);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Fernando Castaño', 'PASAPORTE', 14012345691, 'fernando.castaño@email.com', 14, 14);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Sandra Osorio', 'CC', 15012345692, 'sandra.osorio@email.com', 15, 15);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Esteban Mejía', 'CC', 16012345693, 'esteban.mejia@email.com', 16, 16);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Camila Giraldo', 'NIT', 17012345694, 'camila.giraldo@email.com', 17, 17);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Sebastián Vargas', 'CE', 18012345695, 'sebastian.vargas@email.com', 18, 18);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Andrea Rodríguez', 'TI', 19012345696, 'andrea.rodriguez@email.com', 19, 19);
INSERT INTO usuarios (nombreuser, tipodocuser, numdocuser, correouser, iduser, idalojamiento) VALUES ('Juan Pablo Arango', 'PASAPORTE', 20012345697, 'juan.pablo.arango@email.com', 20, 20);

-- Insertando datos en la tabla 'habitaciones'
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (101, 'SI', 150, 1, 1, 1, 1);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (102, 'SI', 200, 2, 2, 2, 2);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (103, 'NO', 250, 3, 3, 3, 3);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (104, 'SI', 300, 4, 4, 4, 4);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (105, 'NO', 350, 5, 5, 5, 5);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (101, 'SI', 150.00, 6, 6, 6, 6);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (102, 'NO', 200.00, 7, 7, 7, 7);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (103, 'SI', 180.00, 8, 8, 8, 8);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (104, 'NO', 220.00, 9, 9, 9, 9);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (105, 'SI', 250.00, 10, 10, 10, 10);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (201, 'NO', 300.00, 11, 11, 11, 11);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (202, 'SI', 350.00, 12, 12, 12, 12);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (203, 'NO', 320.00, 13, 13, 13, 13);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (204, 'SI', 280.00, 14, 14, 14, 14);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (205, 'NO', 260.00, 15, 15, 15, 15);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (301, 'SI', 200.00, 16, 16, 16, 16);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (302, 'NO', 180.00, 17, 17, 17, 17);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (303, 'SI', 220.00, 18, 18, 18, 18);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (304, 'NO', 240.00, 19, 19, 19, 19);
INSERT INTO habitaciones (numhabitacion, disponible, precionoche, idhotel, idtipo, idalojamiento, idhabitacion) VALUES (305, 'SI', 260.00, 20, 20, 20, 20);

-- Insertando datos en la tabla 'cuentas'
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (5000, 1, 1);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (6000, 2, 2);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (7000, 3, 3);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (8000, 4, 4);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (9000, 5, 5);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (5000, 6, 6);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (7500, 7, 7);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (3000, 8, 8);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (6000, 9, 9);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (4500, 10, 10);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (5200, 11, 11);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (8300, 12, 12);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (6700, 13, 13);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (5400, 14, 14);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (6200, 15, 15);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (3800, 16, 16);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (4900, 17, 17);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (7200, 18, 18);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (8100, 19, 19);
INSERT INTO cuentas (netocuenta, idcuenta, idalojamiento) VALUES (9400, 20, 20);

-- Insertando datos en la tabla 'reservas'
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-05 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-06 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 2);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-07 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), 3, 3);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-08 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), 4, 4);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-09 19:00:00', 'YYYY-MM-DD HH24:MI:SS'), 5, 5);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-10 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 6, 6);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-11 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 7, 7);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-12 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 8, 8);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-13 20:00:00', 'YYYY-MM-DD HH24:MI:SS'), 9, 9);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-14 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 10, 10);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-15 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 11, 11);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-16 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 12, 12);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-17 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 13, 13);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-18 20:00:00', 'YYYY-MM-DD HH24:MI:SS'), 14, 14);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-19 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 15, 15);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-20 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 16, 16);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-21 16:00:00', 'YYYY-MM-DD HH24:MI:SS'), 17, 17);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-22 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 18, 18);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-23 20:00:00', 'YYYY-MM-DD HH24:MI:SS'), 19, 19);
INSERT INTO reservas (horareserva, idreserva, idcuenta) VALUES (TO_DATE('2023-11-24 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 20, 20);

-- Insertando datos en la tabla 'servicios'
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('07:00', 'HH24:MI'), TO_DATE('23:00', 'HH24:MI'), 'Cata de Vinos Premium', 100.00, 'NO', 'SI', 121, 1);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('06:00', 'HH24:MI'), TO_DATE('22:00', 'HH24:MI'), 'Safari Fotográfico', 150.00, 'NO', 'SI', 122, 2);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('09:00', 'HH24:MI'), TO_DATE('22:00', 'HH24:MI'), 'Taller de Cocina Local', 50.00, 'SI', 'SI', 123, 3);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('08:00', 'HH24:MI'), TO_DATE('20:00', 'HH24:MI'), 'Masajes Relajantes a la Orilla del Mar', 75.00, 'NO', 'SI', 124, 4);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('11:00', 'HH24:MI'), TO_DATE('16:00', 'HH24:MI'), 'Noche de Observación Astronómica', 200.00, 'SI', 'SI', 125, 5);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('08:00', 'HH24:MI'), TO_DATE('20:00', 'HH24:MI'), 'Servicio de habitación', 50, 'SI', 'SI', 126, 6);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('09:00', 'HH24:MI'), TO_DATE('22:00', 'HH24:MI'), 'Lavandería express', 30, 'NO', 'SI', 127, 7);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('07:00', 'HH24:MI'), TO_DATE('23:00', 'HH24:MI'), 'Spa y bienestar', 70, 'SI', 'SI', 128, 8);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('06:00', 'HH24:MI'), TO_DATE('22:00', 'HH24:MI'), 'Transporte aeropuerto', 25, 'NO', 'SI', 129, 9);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('10:00', 'HH24:MI'), TO_DATE('18:00', 'HH24:MI'), 'Excursiones guiadas', 40, 'SI', 'SI', 130, 10);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('11:00', 'HH24:MI'), TO_DATE('16:00', 'HH24:MI'), 'Gimnasio', 20, 'NO', 'SI', 131, 11);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('08:30', 'HH24:MI'), TO_DATE('21:00', 'HH24:MI'), 'Desayuno buffet', 15, 'SI', 'SI', 132, 12);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('10:00', 'HH24:MI'), TO_DATE('23:30', 'HH24:MI'), 'Bar nocturno', 60, 'NO', 'SI', 133, 13);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('12:00', 'HH24:MI'), TO_DATE('15:00', 'HH24:MI'), 'Almuerzo especial', 35, 'SI', 'SI', 134, 14);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('19:00', 'HH24:MI'), TO_DATE('23:30', 'HH24:MI'), 'Cena romántica', 80, 'NO', 'SI', 135, 15);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('09:30', 'HH24:MI'), TO_DATE('17:00', 'HH24:MI'), 'Alquiler de bicicletas', 25, 'SI', 'SI', 136, 16);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('08:00', 'HH24:MI'), TO_DATE('20:00', 'HH24:MI'), 'Clases de yoga', 30, 'NO', 'SI', 137, 17);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('08:00', 'HH24:MI'), TO_DATE('22:00', 'HH24:MI'), 'Tour cultural', 45, 'SI', 'SI', 138, 18);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('10:00', 'HH24:MI'), TO_DATE('22:00', 'HH24:MI'), 'Cine al aire libre', 20, 'NO', 'SI', 139, 19);
INSERT INTO servicios (horarioinicial, horariofinal, nombre, costo, cargado, existe, idservicio, idreserva) VALUES (TO_DATE('18:00', 'HH24:MI'), TO_DATE('02:00', 'HH24:MI'), 'Casino', 100, 'SI', 'SI', 140, 20);

-- Insertando datos en la tabla 'bares'
INSERT INTO bares (estilo, idservicio) VALUES ('Frances', 1);
INSERT INTO bares (estilo, idservicio) VALUES ('Italiano', 2);
INSERT INTO bares (estilo, idservicio) VALUES ('Mediterraneo', 3);
INSERT INTO bares (estilo, idservicio) VALUES ('Mexicano', 4);
INSERT INTO bares (estilo, idservicio) VALUES ('Oriental', 5);
INSERT INTO bares (estilo, idservicio) VALUES ('Frances', 6);
INSERT INTO bares (estilo, idservicio) VALUES ('Italiano', 7);
INSERT INTO bares (estilo, idservicio) VALUES ('Mediterraneo', 8);
INSERT INTO bares (estilo, idservicio) VALUES ('Mexicano', 9);
INSERT INTO bares (estilo, idservicio) VALUES ('Oriental', 10);
INSERT INTO bares (estilo, idservicio) VALUES ('Frances', 11);
INSERT INTO bares (estilo, idservicio) VALUES ('Italiano', 12);
INSERT INTO bares (estilo, idservicio) VALUES ('Mediterraneo', 13);
INSERT INTO bares (estilo, idservicio) VALUES ('Mexicano', 14);
INSERT INTO bares (estilo, idservicio) VALUES ('Oriental', 15);
INSERT INTO bares (estilo, idservicio) VALUES ('Frances', 16);
INSERT INTO bares (estilo, idservicio) VALUES ('Italiano', 17);
INSERT INTO bares (estilo, idservicio) VALUES ('Mediterraneo', 18);
INSERT INTO bares (estilo, idservicio) VALUES ('Mexicano', 19);
INSERT INTO bares (estilo, idservicio) VALUES ('Oriental', 20);

-- Insertando datos en la tabla 'restaurantes'
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Frances', 81);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Italiano', 82);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Mediterraneo', 83);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Mexicano', 84);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Oriental', 85);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Italiano', 86);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Mexicano', 87);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Frances', 88);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Mediterraneo', 89);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Oriental', 90);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Italiano', 91);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Mexicano', 92);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Frances', 93);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Mediterraneo', 94);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Oriental', 95);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Italiano', 96);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Mexicano', 97);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Frances', 98);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Mediterraneo', 99);
INSERT INTO restaurantes (estilo, idservicio) VALUES ('Oriental', 100);

-- Insertando datos en la tabla 'tiendas'
INSERT INTO tiendas (tipo, idservicio) VALUES ('Joyeria', 161);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Moda', 162);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Souvenirs', 163);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Supermercado', 164);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Joyeria', 165);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Joyeria', 166);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Moda', 167);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Souvenirs', 168);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Supermercado', 169);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Joyeria', 170);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Moda', 171);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Souvenirs', 172);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Supermercado', 173);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Joyeria', 174);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Moda', 175);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Souvenirs', 176);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Supermercado', 177);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Joyeria', 178);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Moda', 179);
INSERT INTO tiendas (tipo, idservicio) VALUES ('Souvenirs', 180);

-- Insertando datos en la tabla 'gimnasios'
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (20, 'Cintas de correr, bicicletas estáticas', 41);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (15, 'Pesas, máquinas de remo', 42);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (25, 'Elípticas, bancos de pesas', 43);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (30, 'Máquinas de pilates, esterillas', 44);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (10, 'Sacos de boxeo, guantes', 45);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (50, 'Cintas de correr, bicicletas estáticas', 46);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (30, 'Elípticas, máquinas de remo', 47);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (20, 'Pesas libres, bancos de pesas', 48);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (40, 'Estaciones de musculación, kettlebells', 49);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (25, 'Máquinas de leg press, máquinas de lat pull-down', 50);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (35, 'Máquinas Smith, sacos de boxeo', 51);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (45, 'Cintas de correr, estaciones de crossfit', 52);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (55, 'Bicicletas de spinning, máquinas de step', 53);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (15, 'Área de yoga, colchonetas', 54);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (60, 'Máquinas de circuito, torres de cable', 55);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (50, 'Máquinas de pecho, máquinas de hombro', 56);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (30, 'Bancos de pesas ajustables, plataformas de salto', 57);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (40, 'Cintas de correr, bicicletas de aire', 58);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (50, 'Bicicletas estáticas, elípticas', 59);
INSERT INTO gimnasios (capacidad, maquinas, idservicio) VALUES (25, 'Máquinas de cable, máquinas de abducción de piernas', 60);

-- Insertando datos en la tabla 'piscinas'
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (50, 2.5, 61);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (75, 3.0, 62);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (100, 1.5, 63);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (30, 2.0, 64);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (25, 1.2, 65);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (30, 1.5, 66);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (50, 2.0, 67);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (40, 1.2, 68);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (25, 1.0, 69);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (35, 1.8, 70);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (45, 2.5, 71);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (55, 1.4, 72);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (20, 1.6, 73);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (60, 2.2, 74);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (30, 1.5, 75);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (50, 2.0, 76);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (40, 1.2, 77);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (25, 1.0, 78);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (35, 1.8, 79);
INSERT INTO piscinas (capacidad, profundidad, idservicio) VALUES (45, 2.5, 80);

-- Insertando datos en la tabla 'spas'
INSERT INTO spas (capacidad, idservicio) VALUES (10, 141);
INSERT INTO spas (capacidad, idservicio) VALUES (15, 142);
INSERT INTO spas (capacidad, idservicio) VALUES (20, 143);
INSERT INTO spas (capacidad, idservicio) VALUES (5, 144);
INSERT INTO spas (capacidad, idservicio) VALUES (8, 145);
INSERT INTO spas (capacidad, idservicio) VALUES (10, 146);
INSERT INTO spas (capacidad, idservicio) VALUES (15, 147);
INSERT INTO spas (capacidad, idservicio) VALUES (20, 148);
INSERT INTO spas (capacidad, idservicio) VALUES (8, 149);
INSERT INTO spas (capacidad, idservicio) VALUES (12, 150);
INSERT INTO spas (capacidad, idservicio) VALUES (10, 151);
INSERT INTO spas (capacidad, idservicio) VALUES (5, 152);
INSERT INTO spas (capacidad, idservicio) VALUES (18, 153);
INSERT INTO spas (capacidad, idservicio) VALUES (7, 154);
INSERT INTO spas (capacidad, idservicio) VALUES (11, 155);
INSERT INTO spas (capacidad, idservicio) VALUES (16, 156);
INSERT INTO spas (capacidad, idservicio) VALUES (20, 157);
INSERT INTO spas (capacidad, idservicio) VALUES (9, 158);
INSERT INTO spas (capacidad, idservicio) VALUES (14, 159);
INSERT INTO spas (capacidad, idservicio) VALUES (13, 160);

-- Insertando datos en la tabla 'conferencias'
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (100, TO_DATE('2023-06-15', 'YYYY-MM-DD'), TO_DATE('09:00', 'HH24:MI'), 120, 21);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (50, TO_DATE('2023-07-20', 'YYYY-MM-DD'), TO_DATE('13:00', 'HH24:MI'), 90, 22);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (75, TO_DATE('2023-08-10', 'YYYY-MM-DD'), TO_DATE('10:00', 'HH24:MI'), 60, 23);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (30, TO_DATE('2023-09-05', 'YYYY-MM-DD'), TO_DATE('16:00', 'HH24:MI'), 45, 24);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (200, TO_DATE('2023-10-12', 'YYYY-MM-DD'), TO_DATE('08:00', 'HH24:MI'), 180, 25);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (100, TO_DATE('2023-11-10', 'YYYY-MM-DD'), TO_DATE('15:00', 'HH24:MI'), 2, 26);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (150, TO_DATE('2023-11-11', 'YYYY-MM-DD'), TO_DATE('16:00', 'HH24:MI'), 3, 27);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (200, TO_DATE('2023-11-12', 'YYYY-MM-DD'), TO_DATE('17:00', 'HH24:MI'), 1, 28);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (250, TO_DATE('2023-11-13', 'YYYY-MM-DD'), TO_DATE('18:00', 'HH24:MI'), 2, 29);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (300, TO_DATE('2023-11-14', 'YYYY-MM-DD'), TO_DATE('19:00', 'HH24:MI'), 3, 30);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (80, TO_DATE('2023-11-15', 'YYYY-MM-DD'), TO_DATE('20:00', 'HH24:MI'), 1, 31);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (120, TO_DATE('2023-11-16', 'YYYY-MM-DD'), TO_DATE('21:00', 'HH24:MI'), 2, 32);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (130, TO_DATE('2023-11-17', 'YYYY-MM-DD'), TO_DATE('22:00', 'HH24:MI'), 3, 33);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (140, TO_DATE('2023-11-18', 'YYYY-MM-DD'), TO_DATE('23:00', 'HH24:MI'), 1, 34);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (90, TO_DATE('2023-11-19', 'YYYY-MM-DD'), TO_DATE('15:00', 'HH24:MI'), 2, 35);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (110, TO_DATE('2023-11-20', 'YYYY-MM-DD'), TO_DATE('16:00', 'HH24:MI'), 3, 36);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (160, TO_DATE('2023-11-21', 'YYYY-MM-DD'), TO_DATE('17:00', 'HH24:MI'), 1, 37);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (170, TO_DATE('2023-11-22', 'YYYY-MM-DD'), TO_DATE('18:00', 'HH24:MI'), 2, 38);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (180, TO_DATE('2023-11-23', 'YYYY-MM-DD'), TO_DATE('19:00', 'HH24:MI'), 3, 39);
INSERT INTO conferencias (capacidad, fecha, hora, duracion, idservicio) VALUES (190, TO_DATE('2023-11-24', 'YYYY-MM-DD'), TO_DATE('20:00', 'HH24:MI'), 1, 40);

-- Insertando datos en la tabla 'reuniones'
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (30, 150, TO_DATE('2023-11-10', 'YYYY-MM-DD'), TO_DATE('10:00:00', 'HH24:MI:SS'), 2, 101);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (50, 250, TO_DATE('2023-11-11', 'YYYY-MM-DD'), TO_DATE('11:00:00', 'HH24:MI:SS'), 3, 102);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (10, 100, TO_DATE('2023-11-12', 'YYYY-MM-DD'), TO_DATE('09:00:00', 'HH24:MI:SS'), 1.5, 103);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (20, 200, TO_DATE('2023-11-13', 'YYYY-MM-DD'), TO_DATE('14:00:00', 'HH24:MI:SS'), 2.5, 104);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (40, 300, TO_DATE('2023-11-14', 'YYYY-MM-DD'), TO_DATE('16:00:00', 'HH24:MI:SS'), 2, 105);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (50, 200, TO_DATE('2023-11-10', 'YYYY-MM-DD'), TO_DATE('14:00', 'HH24:MI'), 2, 106);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (30, 150, TO_DATE('2023-11-11', 'YYYY-MM-DD'), TO_DATE('10:00', 'HH24:MI'), 1.5, 107);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (100,500, TO_DATE('2023-11-12', 'YYYY-MM-DD'), TO_DATE('16:00', 'HH24:MI'), 3, 108);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (25, 120, TO_DATE('2023-11-13', 'YYYY-MM-DD'), TO_DATE('09:00', 'HH24:MI'), 2, 109);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (40, 250, TO_DATE('2023-11-14', 'YYYY-MM-DD'), TO_DATE('15:00', 'HH24:MI'), 4, 110);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (75, 350, TO_DATE('2023-11-15', 'YYYY-MM-DD'), TO_DATE('13:00', 'HH24:MI'), 2.5, 111);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (20, 100, TO_DATE('2023-11-16', 'YYYY-MM-DD'), TO_DATE('11:00', 'HH24:MI'), 1, 112);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (60, 300, TO_DATE('2023-11-17', 'YYYY-MM-DD'), TO_DATE('17:00', 'HH24:MI'), 3.5, 113);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (35, 180, TO_DATE('2023-11-18', 'YYYY-MM-DD'), TO_DATE('10:30', 'HH24:MI'), 2, 114);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (80, 400, TO_DATE('2023-11-19', 'YYYY-MM-DD'), TO_DATE('14:30', 'HH24:MI'), 3, 115);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (55, 275, TO_DATE('2023-11-20', 'YYYY-MM-DD'), TO_DATE('09:30', 'HH24:MI'), 2, 116);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (90, 450, TO_DATE('2023-11-21', 'YYYY-MM-DD'), TO_DATE('13:30', 'HH24:MI'), 2.5, 117);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (45, 225, TO_DATE('2023-11-22', 'YYYY-MM-DD'), TO_DATE('16:30', 'HH24:MI'), 1.5, 118);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (70, 330, TO_DATE('2023-11-23', 'YYYY-MM-DD'), TO_DATE('12:00', 'HH24:MI'), 3.5, 119);
INSERT INTO reuniones (capacidad, costoadicional, fecha, hora, duracion, idservicio) VALUES (65, 310, TO_DATE('2023-11-24', 'YYYY-MM-DD'), TO_DATE('18:00', 'HH24:MI'), 4, 120);

-- Insertando datos en la tabla 'utensilios'
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('SI', 'Buen estado', 181);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('NO', 'Necesita reparación', 182);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('SI', 'Como nuevo', 183);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('NO', 'Desgastado', 184);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('SI', 'Ligeramente usado', 185);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('NO', 'Dañado', 186);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('SI', 'En buen funcionamiento', 187);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('NO', 'Obsoleto', 188);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('SI', 'Requiere limpieza', 189);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('NO', 'Perdido', 190);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('SI', 'Nuevo', 191);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('NO', 'Roto', 192);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('SI', 'Usable', 193);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('NO', 'Necesita reemplazo', 194);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('SI', 'Buen estado', 195);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('NO', 'Muy desgastado', 196);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('SI', 'Mantenimiento reciente', 197);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('NO', 'Incompleto', 198);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('SI', 'Funcional', 199);
INSERT INTO utensilios (devuelto, estado, idservicio) VALUES ('NO', 'Para descarte', 200);

-- Insertando datos en la tabla 'wifi'
INSERT INTO wifi (anchobanda, idservicio) VALUES (50.5, 201);
INSERT INTO wifi (anchobanda, idservicio) VALUES (75.0, 202);
INSERT INTO wifi (anchobanda, idservicio) VALUES (100.0, 203);
INSERT INTO wifi (anchobanda, idservicio) VALUES (150.0, 204);
INSERT INTO wifi (anchobanda, idservicio) VALUES (200.0, 205);
INSERT INTO wifi (anchobanda, idservicio) VALUES (250.0, 206);
INSERT INTO wifi (anchobanda, idservicio) VALUES (300.0, 207);
INSERT INTO wifi (anchobanda, idservicio) VALUES (350.0, 208);
INSERT INTO wifi (anchobanda, idservicio) VALUES (400.0, 209);
INSERT INTO wifi (anchobanda, idservicio) VALUES (450.0, 210);
INSERT INTO wifi (anchobanda, idservicio) VALUES (500.0, 211);
INSERT INTO wifi (anchobanda, idservicio) VALUES (550.0, 212);
INSERT INTO wifi (anchobanda, idservicio) VALUES (600.0, 213);
INSERT INTO wifi (anchobanda, idservicio) VALUES (650.0, 214);
INSERT INTO wifi (anchobanda, idservicio) VALUES (700.0, 215);
INSERT INTO wifi (anchobanda, idservicio) VALUES (750.0, 216);
INSERT INTO wifi (anchobanda, idservicio) VALUES (800.0, 217);
INSERT INTO wifi (anchobanda, idservicio) VALUES (850.0, 218);
INSERT INTO wifi (anchobanda, idservicio) VALUES (900.0, 219);
INSERT INTO wifi (anchobanda, idservicio) VALUES (950.0, 220);

-- Insertando datos en la tabla 'servispas'
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (60, 100.00, TO_DATE('2023-11-20', 'YYYY-MM-DD'), 141, 1);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (90, 150.00, TO_DATE('2023-11-21', 'YYYY-MM-DD'), 142, 2);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (120, 200.00, TO_DATE('2023-11-22', 'YYYY-MM-DD'), 143, 3);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (30, 50.00, TO_DATE('2023-11-23', 'YYYY-MM-DD'), 144, 4);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (45, 75.00, TO_DATE('2023-11-24', 'YYYY-MM-DD'), 145, 5);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (30, 50.00, TO_DATE('2023-11-01', 'YYYY-MM-DD'), 146, 6);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (45, 75.00, TO_DATE('2023-11-02', 'YYYY-MM-DD'), 147, 7);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (60, 100.00, TO_DATE('2023-11-03', 'YYYY-MM-DD'), 148, 8);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (90, 150.00, TO_DATE('2023-11-04', 'YYYY-MM-DD'), 149, 9);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (120, 200.00, TO_DATE('2023-11-05', 'YYYY-MM-DD'), 150, 10);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (30, 55.00, TO_DATE('2023-11-06', 'YYYY-MM-DD'), 151, 11);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (45, 80.00, TO_DATE('2023-11-07', 'YYYY-MM-DD'), 152, 12);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (60, 105.00, TO_DATE('2023-11-08', 'YYYY-MM-DD'), 153, 13);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (90, 155.00, TO_DATE('2023-11-09', 'YYYY-MM-DD'), 154, 14);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (120, 205.00, TO_DATE('2023-11-10', 'YYYY-MM-DD'), 155, 15);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (30, 60.00, TO_DATE('2023-11-11', 'YYYY-MM-DD'), 156, 16);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (45, 85.00, TO_DATE('2023-11-12', 'YYYY-MM-DD'), 157, 17);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (60, 110.00, TO_DATE('2023-11-13', 'YYYY-MM-DD'), 158, 18);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (90, 160.00, TO_DATE('2023-11-14', 'YYYY-MM-DD'), 159, 19);
INSERT INTO servispas (duracion, costo, fecha, spas_idservicio, idservispas) VALUES (120, 210.00, TO_DATE('2023-11-15', 'YYYY-MM-DD'), 160, 20);

-- Insertando datos en la tabla 'productos'
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Cocktail Margarita', 12.00, 81, 1, 161, 1);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Hamburguesa de Res', 15.00, 82, 2, 162, 2);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Bufanda de Seda', 40.00, 83, 3, 163, 3);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Café Americano', 3.00, 84, 4, 164, 4);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Vino Tinto Reserva', 30.00, 85, 5, 165, 5);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Delicia Marina', 45.00, 86, 6, 166, 6);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Sorbete Amazónico', 15.50, 87, 7, 167, 7);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Tentación de Trufa', 75.00, 88, 8, 168, 8);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Crepúsculo Citrino', 30.00, 89, 9, 169, 9);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Bocado del Chef', 55.00, 90, 10, 170, 10);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Panacea Tropical', 20.00, 91, 11, 171, 11);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Ensueño Andino', 65.00, 92, 12, 172, 12);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Manjar de Cacao', 40.00, 93, 13, 173, 13);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Armonía de Frutos', 25.00, 94, 14, 174, 14);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Elixir de Uva', 60.00, 95, 15, 175, 15);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Explosión de Sabores', 50.00, 96, 16, 176, 16);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Sinfonía de Mariscos', 80.00, 97, 17, 177, 17);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Emoción de Chocolate', 35.00, 98, 18, 178, 18);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Cóctel de la Casa', 22.00, 99, 19, 179, 19);
INSERT INTO productos (nombre, precio, restaurantes_idservicio, bares_idservicio, tiendas_idservicio, idproducto) VALUES ('Amanecer Andaluz', 28.00, 100, 20, 180, 20);

COMMIT;