--SCRIPT DE PRUEBAS--


--RF1: Crear una ciudad-- 

--Crear una ciudad: Exitoso--
INSERT INTO CIUDAD (CODIGO, NOMBRE) VALUES (SECUENCIA_CIUDAD.NEXTVAL, 'PEREIRA');


--Crear ciudad: Nombre repetido--
INSERT INTO CIUDAD (CODIGO, NOMBRE) VALUES (SECUENCIA_CIUDAD.NEXTVAL, 'CALI');

--Crear ciudad: Nombre inválido--
INSERT INTO CIUDAD (CODIGO, NOMBRE) VALUES (SECUENCIA_CIUDAD.NEXTVAL, 'Merequetengue');

--Crear ciudad: Nombre null--
INSERT INTO CIUDAD (CODIGO, NOMBRE) VALUES (SECUENCIA_CIUDAD.NEXTVAL, NULL);

--RF2: Crear una sucursal--

--Crear una sucursal: Exitoso--
INSERT INTO SUCURSAL (ID, NOMBRE, TAMANIO, DIRECCION, TELEFONO, CODIGO_CIUDAD) VALUES (SECUENCIA_SUCURSAL.NEXTVAL, 'Sucursal Bono', 20.0, 'Calle Me Gané el Bono #122-34', '3118873430', 1);


--Crear una sucursal: Nombre null--
INSERT INTO SUCURSAL (ID, NOMBRE, TAMANIO, DIRECCION, TELEFONO, CODIGO_CIUDAD) VALUES (SECUENCIA_SUCURSAL.NEXTVAL, NULL, 20.0, 'Calle Me Gané el Bono #122-34', '3118873430', 1);


--Crear una sucursal: Tamaño null--
INSERT INTO SUCURSAL (ID, NOMBRE, TAMANIO, DIRECCION, TELEFONO, CODIGO_CIUDAD) VALUES (SECUENCIA_SUCURSAL.NEXTVAL, 'Sucursal Tengo Suenio', NULL, 'Universidad de los Alpes', '3153165152', 1);

--Crear sucursal: Tamanio CK mayor cero--
INSERT INTO SUCURSAL (ID, NOMBRE, TAMANIO, DIRECCION, TELEFONO, CODIGO_CIUDAD) VALUES (SECUENCIA_SUCURSAL.NEXTVAL, 'Sucursal Bono' ,0 , 'Calle Me Gané el Bono #122-34', '3118873434', 1);

--Crear sucursal: Direccion null--
INSERT INTO SUCURSAL (ID, NOMBRE, TAMANIO, DIRECCION, TELEFONO, CODIGO_CIUDAD) VALUES (SECUENCIA_SUCURSAL.NEXTVAL, 'Sucursal Tengo Suenio',20.0 ,NULL, '3153165152', 1);

--Crear sucursal: Teléfono null-- 
INSERT INTO SUCURSAL (ID, NOMBRE, TAMANIO, DIRECCION, TELEFONO, CODIGO_CIUDAD) VALUES (SECUENCIA_SUCURSAL.NEXTVAL, 'Sucursal Tengo Suenio' ,20.0 ,'Universidad de los Alpes', NULL, 1);

--Crear sucursal: Teléfono único-- 
INSERT INTO SUCURSAL (ID, NOMBRE, TAMANIO, DIRECCION, TELEFONO, CODIGO_CIUDAD) VALUES (SECUENCIA_SUCURSAL.NEXTVAL, 'Sucursal Miau',20.0 , 'Calle Gatuna #145-34, apto 34', '3118873434', 1);

--Crear sucursal: FK codigoCiudad null--
INSERT INTO SUCURSAL (ID, NOMBRE, TAMANIO, DIRECCION, TELEFONO, CODIGO_CIUDAD) VALUES (SECUENCIA_SUCURSAL.NEXTVAL, 'Sucursal Gato',20.0 , 'Calle Me Gané el Bono #122-34', '3118873494', NULL);

--Crear sucursal: FK no existente--
INSERT INTO SUCURSAL (ID, NOMBRE, TAMANIO, DIRECCION, TELEFONO, CODIGO_CIUDAD) VALUES (SECUENCIA_SUCURSAL.NEXTVAL, 'Sucursal Gato' , 20.0 , 'Universidad de los Alpes', '3153165152', 0);


--RF3: Crear y Borrar una Bodega--

--Crear Bodega: Exitoso--
INSERT INTO BODEGA (ID, NOMBRE, TAMANIO, CAPACIDAD, ID_SUCURSAL)
VALUES (SECUENCIA_BODEGA.NEXTVAL, 'Bodega de los Dioses', 22, 1, 2);


--Crear Bodega: Nombre null--
INSERT INTO BODEGA (ID, NOMBRE, TAMANIO, CAPACIDAD, ID_SUCURSAL)
VALUES (SECUENCIA_BODEGA.NEXTVAL, NULL, 22, 1, 2);

--Crear Bodega: Tamanio null--
INSERT INTO BODEGA (ID, NOMBRE, TAMANIO, CAPACIDAD, ID_SUCURSAL)
VALUES (SECUENCIA_BODEGA.NEXTVAL, 'Bodega de los Dioses', NULL, 1, 2);

--Crear Bodega: Tamanio CK mayor cero--
INSERT INTO BODEGA (ID, NOMBRE, TAMANIO, CAPACIDAD, ID_SUCURSAL)
VALUES (SECUENCIA_BODEGA.NEXTVAL, 'Bodega de los Dioses', -1, 1, 2);

--Crear Bodega: Capacidad null--
INSERT INTO BODEGA (ID, NOMBRE, TAMANIO, CAPACIDAD, ID_SUCURSAL)
VALUES (SECUENCIA_BODEGA.NEXTVAL, 'Bodega de los Dioses', 22, NULL, 2);

--Crear Bodega: Capacidad CK mayor cero--
INSERT INTO BODEGA (ID, NOMBRE, TAMANIO, CAPACIDAD, ID_SUCURSAL)
VALUES (SECUENCIA_BODEGA.NEXTVAL, 'Bodega de los Dioses', 22, -2, 2);

--Crear Bodega: FK idSucursal null--
INSERT INTO BODEGA (ID, NOMBRE, TAMANIO, CAPACIDAD, ID_SUCURSAL)
VALUES (SECUENCIA_BODEGA.NEXTVAL, 'Bodega de los Dioses', 22, 1, NULL);

--Crear Bodega: FK no existente--
INSERT INTO BODEGA (ID, NOMBRE, TAMANIO, CAPACIDAD, ID_SUCURSAL)
VALUES (SECUENCIA_BODEGA.NEXTVAL, 'Bodega de los Dioses', 22, 1, 0);

--Borrar Bodega: Exitoso--
DELETE FROM BODEGA WHERE ID = 5;

--Borrar Bodega: PK ID no existente--
DELETE FROM BODEGA WHERE ID = -1;


--RF4: Crear y Actualizar Proveedores--

--Crear Proveedor: Exitoso--
INSERT INTO PROVEEDOR (NIT, NOMBRE, DIRECCION, NOMBRE_PERSONA_CONTACTO, TELEFONO_PERSONA_CONTACTO) 
VALUES ('900222444-5', 'Juan Avelino', 'Calle Sistemas Transaccionales', 'Shawn Cabello', '3102604332');

--Crear Proveedor:  PK NIT repetida--
INSERT INTO PROVEEDOR (NIT, NOMBRE, DIRECCION, NOMBRE_PERSONA_CONTACTO, TELEFONO_PERSONA_CONTACTO)
VALUES ('900123456-7', 'Maria Pinzon', 'Calle busquela', 'Camila Cabello', '3103103131');

--Crear Proveedor: NIT null--
INSERT INTO PROVEEDOR (NIT, NOMBRE, DIRECCION, NOMBRE_PERSONA_CONTACTO, TELEFONO_PERSONA_CONTACTO)
VALUES (NULL, 'Billie', 'Calle busquela', 'Camila Cabello', '3102604096');

--Crear Proveedor: Nombre null--
INSERT INTO PROVEEDOR (NIT, NOMBRE, DIRECCION, NOMBRE_PERSONA_CONTACTO, TELEFONO_PERSONA_CONTACTO)
VALUES ('900222445-6', NULL, 'Calle busquela', 'Camila Cabello', '3102604096');

--Crear Proveedor: Direccion null--
INSERT INTO PROVEEDOR (NIT, NOMBRE, DIRECCION, NOMBRE_PERSONA_CONTACTO, TELEFONO_PERSONA_CONTACTO)
VALUES ('900222445-0', 'Juan Avelino', NULL, 'Camila Cabello', '3113112323');

--Crear Proveedor: Nombre Persona Contacto Null--
INSERT INTO PROVEEDOR (NIT, NOMBRE, DIRECCION, NOMBRE_PERSONA_CONTACTO, TELEFONO_PERSONA_CONTACTO)
VALUES ('999922444-2', 'Juan Avelino', 'Calle busquela', NULL, '3199999999');

--Crear Proveedor: TelefonoPersonaContacto null--
INSERT INTO PROVEEDOR (NIT, NOMBRE, DIRECCION, NOMBRE_PERSONA_CONTACTO, TELEFONO_PERSONA_CONTACTO)
VALUES ('900222999-2', 'Juan Avelino', 'Calle busquela', 'Camila Cabello', NULL);

--Crear Proveedor: TelefonoPersonaContacto unico--
INSERT INTO PROVEEDOR (NIT, NOMBRE, DIRECCION, NOMBRE_PERSONA_CONTACTO, TELEFONO_PERSONA_CONTACTO)
VALUES ('555444444-5', 'Juan Rasta', 'Calle busquela', 'Sandra Cabello', '3203456789');

--Actualizar Proveedor: Exitoso--
UPDATE PROVEEDOR
SET NOMBRE = 'Armando Mendoza Saenz', DIRECCION = 'Casita de los lobos siberianos', NOMBRE_PERSONA_CONTACTO = 'Pipe Bueno', TELEFONO_PERSONA_CONTACTO = '3114567322'
WHERE NIT = '900123456-7';

--Actualizar Proveedor: PK NIT no existe--
UPDATE PROVEEDOR
SET NOMBRE = 'Armando Mendoza Saenz', DIRECCION = 'Casita de los lobos siberianos', NOMBRE_PERSONA_CONTACTO = 'Pipe Bueno', TELEFONO_PERSONA_CONTACTO = '3114567322'
WHERE NIT = '0';

--Actualizar Proveedor: Nombre null--
UPDATE PROVEEDOR
SET NOMBRE = NULL, DIRECCION = 'Casita de los lobos siberianos', NOMBRE_PERSONA_CONTACTO = 'Pipe Bueno', TELEFONO_PERSONA_CONTACTO = '3114567322'
WHERE NIT = '900123456-7';


--Actualizar Proveedor: Direccion null--
UPDATE PROVEEDOR
SET NOMBRE = 'Armando Mendoza Saenz', DIRECCION = NULL, NOMBRE_PERSONA_CONTACTO = 'Pipe Bueno', TELEFONO_PERSONA_CONTACTO = '3114567322'
WHERE NIT = '900123456-7';

--Actualizar Proveedor: NombrePersonaContacto null--
UPDATE PROVEEDOR
SET NOMBRE = 'Armando Mendoza Saenz', DIRECCION = 'Casita de los lobos siberianos', NOMBRE_PERSONA_CONTACTO = NULL, TELEFONO_PERSONA_CONTACTO = '3114567322'
WHERE NIT = '900123456-7';

--Actualizar Proveedor: TelefonoPersonaContacto null--
UPDATE PROVEEDOR
SET NOMBRE = 'Armando Mendoza Saenz', DIRECCION = 'Casita de los lobos siberianos', NOMBRE_PERSONA_CONTACTO = 'Pipe Bueno', TELEFONO_PERSONA_CONTACTO = NULL
WHERE NIT = '900123456-7';

--Actualizar Proveedor: TelefonoPersonaContacto unico--
UPDATE PROVEEDOR
SET NOMBRE = 'Armando Mendoza Saenz', DIRECCION = 'Casita de los lobos siberianos', NOMBRE_PERSONA_CONTACTO = 'Pipe Bueno', TELEFONO_PERSONA_CONTACTO = '3102345678'
WHERE NIT = '900123456-7';


--RF5: Crear y Leer una Categoría--

--Crear Categoría: Exitoso--
INSERT INTO CATEGORIA (CODIGO, NOMBRE, DESCRIPCION, CARACTERISTICAS_ALMACENAMIENTO)
VALUES (SECUENCIA_CATEGORIA.NEXTVAL, 'ELECTRODOMÉSTICO', 'Aparatos eléctricos de uso domestico', 'Almacenamiento en lugares secos y ventilados');

--Crear Categoría: Nombre ya existente--
INSERT INTO CATEGORIA (CODIGO, NOMBRE, DESCRIPCION, CARACTERISTICAS_ALMACENAMIENTO)
VALUES (SECUENCIA_CATEGORIA.NEXTVAL, 'PERECEDERO', 'productos que se pudren', 'Almacenamiento en lugares secos y ventilados');

--Crear Categoría: Nombre no permitido--
INSERT INTO CATEGORIA (CODIGO, NOMBRE, DESCRIPCION, CARACTERISTICAS_ALMACENAMIENTO)
VALUES (SECUENCIA_CATEGORIA.NEXTVAL, 'Escalada', 'Productos de escalada para aventureros', 'Guardar en lugares lejos de humedad');


--Crear Categoría: Nombre null--
INSERT INTO CATEGORIA (CODIGO, NOMBRE, DESCRIPCION, CARACTERISTICAS_ALMACENAMIENTO)
VALUES (SECUENCIA_CATEGORIA.NEXTVAL, NULL, 'Productos de escalada para aventureros', 'Guardar en lugares lejos de humedad');


--Crear Categoría: Descripcion null--
INSERT INTO CATEGORIA (CODIGO, NOMBRE, DESCRIPCION, CARACTERISTICAS_ALMACENAMIENTO)
VALUES (SECUENCIA_CATEGORIA.NEXTVAL, 'ACAMPADA', NULL, 'Guardar en lugares lejos de humedad');

--Crear Categoría: Caracteristicas Almacenamiento null--
INSERT INTO CATEGORIA (CODIGO, NOMBRE, DESCRIPCION, CARACTERISTICAS_ALMACENAMIENTO)
VALUES (SECUENCIA_CATEGORIA.NEXTVAL, 'ACAMPADA', 'Productos para salir a acampar con tus amigos, lo cual deberías hacer en semana de receso', NULL);

--Leer categoría por código: válido Exitoso --
SELECT * FROM CATEGORIA WHERE CODIGO = 6;

--Leer categoría por código: código no existe--
SELECT * FROM CATEGORIA WHERE CODIGO = 0;

--Leer categoría por nombre: válido Exitoso--
SELECT * FROM CATEGORIA WHERE NOMBRE = 'PERECEDERO';

--Leer categoría por nombre: nombre no existe--
SELECT * FROM CATEGORIA WHERE NOMBRE = 'MIAU';




--RF6: Crear, leer y actualizar un Producto--

--Crear producto: Exitoso--
INSERT INTO PRODUCTO (IDENTIFICADOR, NOMBRE, COSTO_EN_BODEGA, PRESENTACION, CANTIDAD_PRESENTACION, UNIDAD_MEDIDA, VOLUMEN_EMPAQUE, PESO_EMPAQUE, FECHA_EXPIRACION, CODIGO_DE_BARRAS, CLASIFICACION_CATEGORIA)
VALUES (SECUENCIA_PRODUCTO.NEXTVAL, 'Clorox', 60, 'Botella de clorox. Tomada por Taka', 600, 'ML', '300 cm3', '100 gr', TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'a0a0a0a0a5', 3);

--Crear producto: Clasificacion Categoria null--
INSERT INTO PRODUCTO (IDENTIFICADOR, NOMBRE, COSTO_EN_BODEGA, PRESENTACION, CANTIDAD_PRESENTACION, UNIDAD_MEDIDA, VOLUMEN_EMPAQUE, PESO_EMPAQUE, FECHA_EXPIRACION, CODIGO_DE_BARRAS, CLASIFICACION_CATEGORIA)
VALUES (SECUENCIA_PRODUCTO.NEXTVAL, 'Clorox', 60, 'Botella de clorox. Tomada por Taka', 600, 'ML', '300 cm3', '100 gr', TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'a0a0a0a0a0', NULL);


--Crear producto: Clasificacion Categoria no existente--
INSERT INTO PRODUCTO (IDENTIFICADOR, NOMBRE, COSTO_EN_BODEGA, PRESENTACION, CANTIDAD_PRESENTACION, UNIDAD_MEDIDA, VOLUMEN_EMPAQUE, PESO_EMPAQUE, FECHA_EXPIRACION, CODIGO_DE_BARRAS, CLASIFICACION_CATEGORIA)
VALUES (SECUENCIA_PRODUCTO.NEXTVAL, 'Clorox', 60, 'Botella de clorox. Tomada por Taka', 600, 'ML', '300 cm3', '100 gr', TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'a0a0a0a0a0', 1000);


--Crear producto: Código de Barras ya existente--
INSERT INTO PRODUCTO (IDENTIFICADOR, NOMBRE, COSTO_EN_BODEGA, PRESENTACION, CANTIDAD_PRESENTACION, UNIDAD_MEDIDA, VOLUMEN_EMPAQUE, PESO_EMPAQUE, FECHA_EXPIRACION, CODIGO_DE_BARRAS, CLASIFICACION_CATEGORIA)
VALUES (SECUENCIA_PRODUCTO.NEXTVAL, 'Puff', 600, 'Puff para sentarse bien comodin', 2000, 'GR', '3000 cm3', '100 gr', NULL, 'a0a0a0a0a0', 6);


--Crear producto: Código de Barras null--
INSERT INTO PRODUCTO (IDENTIFICADOR, NOMBRE, COSTO_EN_BODEGA, PRESENTACION, CANTIDAD_PRESENTACION, UNIDAD_MEDIDA, VOLUMEN_EMPAQUE, PESO_EMPAQUE, FECHA_EXPIRACION, CODIGO_DE_BARRAS, CLASIFICACION_CATEGORIA)
VALUES (SECUENCIA_PRODUCTO.NEXTVAL, 'Clorox', 60, 'Botella de clorox. Tomada por Taka', 600, 'ML', '300 cm3', '100 gr', TO_DATE('2026-04-04', 'YYYY-MM-DD'), NULL, 3);


--Crear producto: Peso Empaque null--
INSERT INTO PRODUCTO (IDENTIFICADOR, NOMBRE, COSTO_EN_BODEGA, PRESENTACION, CANTIDAD_PRESENTACION, UNIDAD_MEDIDA, VOLUMEN_EMPAQUE, PESO_EMPAQUE, FECHA_EXPIRACION, CODIGO_DE_BARRAS, CLASIFICACION_CATEGORIA)
VALUES (SECUENCIA_PRODUCTO.NEXTVAL, 'Clorox', 60, 'Botella de clorox. Tomada por Taka', 600, 'ML', '300 cm3', NULL, TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'a0a0a0a0a0', 3);


--Crear producto: Volumen Empaque null--
INSERT INTO PRODUCTO (IDENTIFICADOR, NOMBRE, COSTO_EN_BODEGA, PRESENTACION, CANTIDAD_PRESENTACION, UNIDAD_MEDIDA, VOLUMEN_EMPAQUE, PESO_EMPAQUE, FECHA_EXPIRACION, CODIGO_DE_BARRAS, CLASIFICACION_CATEGORIA)
VALUES (SECUENCIA_PRODUCTO.NEXTVAL, 'Clorox', 60, 'Botella de clorox. Tomada por Taka', 600, 'ML', NULL, '100 gr', TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'a0a0a0a0a0', 3);

--Crear producto: Unidad Empaque null--
INSERT INTO PRODUCTO (IDENTIFICADOR, NOMBRE, COSTO_EN_BODEGA, PRESENTACION, CANTIDAD_PRESENTACION, UNIDAD_MEDIDA, VOLUMEN_EMPAQUE, PESO_EMPAQUE, FECHA_EXPIRACION, CODIGO_DE_BARRAS, CLASIFICACION_CATEGORIA)
VALUES (SECUENCIA_PRODUCTO.NEXTVAL, 'Clorox', 60, 'Botella de clorox. Tomada por Taka', 600, NULL, '300 cm3', '100 gr', TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'a0a0a0a0a0', 3);

--Crear producto: Cantidad Presentacion null--
INSERT INTO PRODUCTO (IDENTIFICADOR, NOMBRE, COSTO_EN_BODEGA, PRESENTACION, CANTIDAD_PRESENTACION, UNIDAD_MEDIDA, VOLUMEN_EMPAQUE, PESO_EMPAQUE, FECHA_EXPIRACION, CODIGO_DE_BARRAS, CLASIFICACION_CATEGORIA)
VALUES (SECUENCIA_PRODUCTO.NEXTVAL, 'Clorox', 60, 'Botella de clorox. Tomada por Taka', 600, NULL, '300 cm3', '100 gr', TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'a0a0a0a0a0', 3);


--Crear producto: Presentacion null--
INSERT INTO PRODUCTO (IDENTIFICADOR, NOMBRE, COSTO_EN_BODEGA, PRESENTACION, CANTIDAD_PRESENTACION, UNIDAD_MEDIDA, VOLUMEN_EMPAQUE, PESO_EMPAQUE, FECHA_EXPIRACION, CODIGO_DE_BARRAS, CLASIFICACION_CATEGORIA)
VALUES (SECUENCIA_PRODUCTO.NEXTVAL, 'Clorox', 60, NULL, 600, 'ML', '300 cm3', '100 gr', TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'a0a0a0a0a0', 3);

--Crear producto: Costo En bodega null--
INSERT INTO PRODUCTO (IDENTIFICADOR, NOMBRE, COSTO_EN_BODEGA, PRESENTACION, CANTIDAD_PRESENTACION, UNIDAD_MEDIDA, VOLUMEN_EMPAQUE, PESO_EMPAQUE, FECHA_EXPIRACION, CODIGO_DE_BARRAS, CLASIFICACION_CATEGORIA)
VALUES (SECUENCIA_PRODUCTO.NEXTVAL, 'Clorox', NULL, 'Botella de clorox. Tomada por Taka', 600, 'ML', '300 cm3', '100 gr', TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'a0a0a0a0a0', 3);

--Crear producto: Nombre null--
INSERT INTO PRODUCTO (IDENTIFICADOR, NOMBRE, COSTO_EN_BODEGA, PRESENTACION, CANTIDAD_PRESENTACION, UNIDAD_MEDIDA, VOLUMEN_EMPAQUE, PESO_EMPAQUE, FECHA_EXPIRACION, CODIGO_DE_BARRAS, CLASIFICACION_CATEGORIA)
VALUES (SECUENCIA_PRODUCTO.NEXTVAL, NULL, 60, 'Botella de clorox. Tomada por Taka', 600, 'ML', '300 cm3', '100 gr', TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'a0a0a0a0a0', 3);


--Leer producto por identificador: Exitoso--
SELECT * FROM PRODUCTO WHERE IDENTIFICADOR = 1;

--Leer producto por identificador: Producto inválido--
SELECT * FROM PRODUCTO WHERE IDENTIFICADOR = 90;

--Actualizar producto: Exitoso--
UPDATE PRODUCTO
SET NOMBRE = 'Cloroxin', COSTO_EN_BODEGA = 500, PRESENTACION = 'Botella de cloroxin. Tomada por Takaxin', CANTIDAD_PRESENTACION = 500, UNIDAD_MEDIDA = 'ML', VOLUMEN_EMPAQUE = '500 cm3', PESO_EMPAQUE = '500 gr', FECHA_EXPIRACION = TO_DATE('2027-12-12', 'YYYY-MM-DD'), CODIGO_DE_BARRAS = 'a0a0a0a0a1', CLASIFICACION_CATEGORIA = 3
WHERE IDENTIFICADOR = 1;


--Actualizar producto: Categoría no existente--
UPDATE PRODUCTO
SET NOMBRE = 'Cloroxin', COSTO_EN_BODEGA = 500, PRESENTACION = 'Botella de cloroxin. Tomada por Takaxin', CANTIDAD_PRESENTACION = 500, UNIDAD_MEDIDA = 'ML', VOLUMEN_EMPAQUE = '500 cm3', PESO_EMPAQUE = '500 gr', FECHA_EXPIRACION = TO_DATE('2027-12-12', 'YYYY-MM-DD'), CODIGO_DE_BARRAS = 'a0a0a0a0a1', CLASIFICACION_CATEGORIA = 300
WHERE IDENTIFICADOR = 1;

--Actualizar producto: Clasificacion categoria null--
UPDATE PRODUCTO
SET NOMBRE = 'Cloroxin', COSTO_EN_BODEGA = 500, PRESENTACION = 'Botella de cloroxin. Tomada por Takaxin', CANTIDAD_PRESENTACION = 500, UNIDAD_MEDIDA = 'ML', VOLUMEN_EMPAQUE = '500 cm3', PESO_EMPAQUE = '500 gr', FECHA_EXPIRACION = TO_DATE('2026-04-04', 'YYYY-MM-DD'), CODIGO_DE_BARRAS = 'a0a0a0a0a5', CLASIFICACION_CATEGORIA = NULL
WHERE IDENTIFICADOR = 1;

--Actualizar producto: Peso Empaque null--
UPDATE PRODUCTO
SET NOMBRE = 'Cloroxin', COSTO_EN_BODEGA = 500, PRESENTACION = 'Botella de cloroxin. Tomada por Takaxin', CANTIDAD_PRESENTACION = 500, UNIDAD_MEDIDA = 'ML', VOLUMEN_EMPAQUE = '500 cm3', PESO_EMPAQUE = NULL, FECHA_EXPIRACION = TO_DATE('2027-12-12', 'YYYY-MM-DD'), CODIGO_DE_BARRAS = 'a0a0a0a0a1', CLASIFICACION_CATEGORIA = 3
WHERE IDENTIFICADOR = 1;


--Actualizar producto: Volumen Empaque null--
UPDATE PRODUCTO
SET NOMBRE = 'Cloroxin', COSTO_EN_BODEGA = 500, PRESENTACION = 'Botella de cloroxin. Tomada por Takaxin', CANTIDAD_PRESENTACION = 500, UNIDAD_MEDIDA = 'ML', VOLUMEN_EMPAQUE = NULL, PESO_EMPAQUE = '500 gr', FECHA_EXPIRACION = TO_DATE('2027-12-12', 'YYYY-MM-DD'), CODIGO_DE_BARRAS = 'a0a0a0a0a1', CLASIFICACION_CATEGORIA = 3
WHERE IDENTIFICADOR = 1;

--Actualizar producto: Unidad medida null--
UPDATE PRODUCTO
SET NOMBRE = 'Cloroxin', COSTO_EN_BODEGA = 500, PRESENTACION = 'Botella de cloroxin. Tomada por Takaxin', CANTIDAD_PRESENTACION = 500, UNIDAD_MEDIDA = NULL, VOLUMEN_EMPAQUE = '500 cm3', PESO_EMPAQUE = '500 gr', FECHA_EXPIRACION = TO_DATE('2027-12-12', 'YYYY-MM-DD'), CODIGO_DE_BARRAS = 'a0a0a0a0a1', CLASIFICACION_CATEGORIA = 3
WHERE IDENTIFICADOR = 1;


--Actualizar producto: Cantidad presentación null--
UPDATE PRODUCTO
SET NOMBRE = 'Cloroxin', COSTO_EN_BODEGA = 500, PRESENTACION = 'Botella de cloroxin. Tomada por Takaxin', CANTIDAD_PRESENTACION = NULL, UNIDAD_MEDIDA = 'ML', VOLUMEN_EMPAQUE = '500 cm3', PESO_EMPAQUE = '500 gr', FECHA_EXPIRACION = TO_DATE('2027-12-12', 'YYYY-MM-DD'), CODIGO_DE_BARRAS = 'a0a0a0a0a1', CLASIFICACION_CATEGORIA = 3
WHERE IDENTIFICADOR = 1;


--Actualizar producto: Presentación null--
UPDATE PRODUCTO
SET NOMBRE = 'Cloroxin', COSTO_EN_BODEGA = 500, PRESENTACION = NULL, CANTIDAD_PRESENTACION = 500, UNIDAD_MEDIDA = 'ML', VOLUMEN_EMPAQUE = '500 cm3', PESO_EMPAQUE = '500 gr', FECHA_EXPIRACION = TO_DATE('2027-12-12', 'YYYY-MM-DD'), CODIGO_DE_BARRAS = 'a0a0a0a0a1', CLASIFICACION_CATEGORIA = 3
WHERE IDENTIFICADOR = 1;

--Actualizar producto: Costo en Bodega null--
UPDATE PRODUCTO
SET NOMBRE = 'Cloroxin', COSTO_EN_BODEGA = NULL, PRESENTACION = 'Botella de cloroxin. Tomada por Takaxin', CANTIDAD_PRESENTACION = 500, UNIDAD_MEDIDA = 'ML', VOLUMEN_EMPAQUE = '500 cm3', PESO_EMPAQUE = '500 gr', FECHA_EXPIRACION = TO_DATE('2027-12-12', 'YYYY-MM-DD'), CODIGO_DE_BARRAS = 'a0a0a0a0a1', CLASIFICACION_CATEGORIA = 3
WHERE IDENTIFICADOR = 1;


--Actualizar producto: Nombre null--
UPDATE PRODUCTO
SET NOMBRE = NULL, COSTO_EN_BODEGA = 500, PRESENTACION = 'Botella de cloroxin. Tomada por Takaxin', CANTIDAD_PRESENTACION = 500, UNIDAD_MEDIDA = 'ML', VOLUMEN_EMPAQUE = '500 cm3', PESO_EMPAQUE = '500 gr', FECHA_EXPIRACION = TO_DATE('2027-12-12', 'YYYY-MM-DD'), CODIGO_DE_BARRAS = 'a0a0a0a0a1', CLASIFICACION_CATEGORIA = 3
WHERE IDENTIFICADOR = 1;


--Actualizar producto: Identificador no existente--
UPDATE PRODUCTO
SET NOMBRE = 'Cloroxin', COSTO_EN_BODEGA = 500, PRESENTACION = 'Botella de cloroxin. Tomada por Takaxin', CANTIDAD_PRESENTACION = 500, UNIDAD_MEDIDA = 'ML', VOLUMEN_EMPAQUE = '500 cm3', PESO_EMPAQUE = '500 gr', FECHA_EXPIRACION = TO_DATE('2027-12-12', 'YYYY-MM-DD'), CODIGO_DE_BARRAS = 'a0a0a0a0a1', CLASIFICACION_CATEGORIA = 3
WHERE IDENTIFICADOR = 4477;


--RF7: Crear una Orden de Compra--

--Crear Orden de Compra: Exitoso--
INSERT INTO ORDEN_DE_COMPRA (NUMERO, FECHA_ENTREGA, ESTADO, FECHA_CREACION, ID_SUCURSAL, NIT_PROVEEDOR)
VALUES (SECUENCIA_ORDEN_DE_COMPRA.NEXTVAL, TO_DATE('2026-04-04', 'YYYY-MM-DD'),'VIGENTE', SYSDATE, 1, '900345678-9');

SELECT * FROM ORDEN_DE_COMPRA WHERE NIT_PROVEEDOR= '900345678-9' AND ESTADO = 'VIGENTE';

--Crear Orden de Compra: Nit Proveedor null--
INSERT INTO ORDEN_DE_COMPRA (NUMERO, FECHA_ENTREGA, ESTADO, FECHA_CREACION, ID_SUCURSAL, NIT_PROVEEDOR)
VALUES (SECUENCIA_ORDEN_DE_COMPRA.NEXTVAL, TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'VIGENTE', SYSDATE, 1, NULL);



--Crear Orden de Compra: Nit Proveedor no existente--
INSERT INTO ORDEN_DE_COMPRA (NUMERO, FECHA_ENTREGA, ESTADO, FECHA_CREACION, ID_SUCURSAL, NIT_PROVEEDOR)
VALUES (SECUENCIA_ORDEN_DE_COMPRA.NEXTVAL, TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'VIGENTE', SYSDATE, 1, 'no existe');


--Crear Orden de Compra: Id Sucursal null--
INSERT INTO ORDEN_DE_COMPRA (NUMERO, FECHA_ENTREGA, ESTADO, FECHA_CREACION, ID_SUCURSAL, NIT_PROVEEDOR)
VALUES (SECUENCIA_ORDEN_DE_COMPRA.NEXTVAL, TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'VIGENTE', SYSDATE, NULL, '900345678-9');


--Crear Orden de Compra: Id Sucursal no existente--
INSERT INTO ORDEN_DE_COMPRA (NUMERO, FECHA_ENTREGA, ESTADO, FECHA_CREACION, ID_SUCURSAL, NIT_PROVEEDOR)
VALUES (SECUENCIA_ORDEN_DE_COMPRA.NEXTVAL, TO_DATE('2026-04-04', 'YYYY-MM-DD'), 'VIGENTE', SYSDATE, 1000, '900345678-9');


--Crear Orden de Compra: Fecha Entrega null--
INSERT INTO ORDEN_DE_COMPRA (NUMERO, FECHA_ENTREGA, ESTADO, FECHA_CREACION, ID_SUCURSAL, NIT_PROVEEDOR)
VALUES (SECUENCIA_ORDEN_DE_COMPRA.NEXTVAL, NULL, 'VIGENTE', SYSDATE, 1, '900345678-9');



--RF8: Actualizar una Orden de Compra--

--Actualizar Orden de Compra: Exitoso--
UPDATE ORDEN_DE_COMPRA
SET ESTADO = 'ENTREGADA'
WHERE NUMERO = 2;


--Actualizar Orden de Compra: Número Inválido--
UPDATE ORDEN_DE_COMPRA
SET FECHA_ENTREGA = TO_DATE('2026-04-04', 'YYYY-MM-DD'), ID_SUCURSAL = 1, NIT_PROVEEDOR = '900345678-9'
WHERE NUMERO = 0;



--RF9: Mostrar todas las Ordenes de Compra--

SELECT OC.*
FROM ORDEN_DE_COMPRA OC
INNER JOIN SUCURSAL S ON OC.ID_SUCURSAL = S.ID
INNER JOIN CIUDAD C ON S.CODIGO_CIUDAD = C.CODIGO
INNER JOIN PROVEEDOR P ON OC.NIT_PROVEEDOR = P.NIT;