
create sequence proyecto_sequence;

CREATE TABLE PRESTAMOS
( ID NUMBER,
  ESTADO VARCHAR2(255 BYTE) NOT NULL,
  TIPO VARCHAR2(255 BYTE) NOT NULL,
  MONTO DECIMAL(10,2) NOT NULL,
  INTERES DECIMAL(10,2) NOT NULL,
  NUMERO_CUOTAS NUMBER NOT NULL,
  DIA_MES_PAGAR_CUOTA VARCHAR2(255 BYTE) NOT NULL,
  VALOR_CUOTA DECIMAL(10,2) NOT NULL,
  CLIENTE NUMBER NOT NULL,
  GERENTE_CREADOR VARCHAR2(255 BYTE) NOT NULL,
  SALDO_PENDIENTE DECIMAL(10,2) NOT NULL,
  CONSTRAINT PRESTAMOS_PK PRIMARY KEY (ID));
  
ALTER TABLE PRESTAMOS
ADD CONSTRAINT ck_prestamos
    CHECK (ESTADO IN('Solicitado','Aprobado','Rechazado','Pagado'))
ENABLE;

ALTER TABLE PRESTAMOS
ADD CONSTRAINT fk_prestamos_a_clientes
    FOREIGN KEY (CLIENTE)
    REFERENCES CLIENTES(ID)
ENABLE;

--------------------------------------
CREATE TABLE CUENTAS
( ID NUMBER,
  NUMERO_CUENTA VARCHAR2(255 BYTE),
  ESTADO VARCHAR2(255 BYTE) NOT NULL,
  SALDO DECIMAL(10,2) NOT NULL,
  TIPO VARCHAR2(255 BYTE) NOT NULL,
  CLIENTE NUMBER,
  ULTIMA_TRANSACCION DATE NOT NULL,
  GERENTE_OFICINA_CREADOR NUMBER NOT NULL,
  FECHA_CREACION DATE NOT NULL,
  CONSTRAINT CUENTAS_PK PRIMARY KEY (ID));
  
ALTER TABLE CUENTAS
ADD CONSTRAINT ck_estado
    CHECK (ESTADO IN('Activa','Cerrada','Desactivada'))
ENABLE;

ALTER TABLE CUENTAS
ADD CONSTRAINT ck_tipo
    CHECK (TIPO IN('Ahorros','Corriente','AFC'))
ENABLE;

ALTER TABLE CUENTAS
ADD CONSTRAINT fk_cuentas_a_clientes
    FOREIGN KEY (CLIENTE)
    REFERENCES CLIENTES(ID)
ENABLE;
---------------------------------------

CREATE TABLE OPERACIONES_CUENTAS
( ID NUMBER,
  TIPO_OPERACION VARCHAR2(255 BYTE) NOT NULL,
  FECHA DATE NOT NULL,
  CUENTA_SALIDA VARCHAR2(255 BYTE) NOT NULL,
  MONTO_OPERACION DECIMAL(10,2) NOT NULL,
  CLIENTE VARCHAR2(255 BYTE) NOT NULL,
  PUNTO_ATENCION NUMBER NOT NULL,
  CUENTA_LLEGADA VARCHAR2(255 BYTE),
  CONSTRAINT OPERACIONES_CUENTAS_PK PRIMARY KEY (ID));
  
ALTER TABLE OPERACIONES_CUENTAS
ADD CONSTRAINT ck_tipo_operacion
    CHECK (TIPO_OPERACION IN('Consignacion','Retiro','Transferencia','Pago cuota extraordinaria','Pago cuota ordinaria'))
ENABLE;

ALTER TABLE OPERACIONES_CUENTAS
ADD CONSTRAINT fk_operaciones_cuentas_a_clientes
    FOREIGN KEY (PUNTO_ATENCION)
    REFERENCES PUNTOS_ATENCION(ID)
ENABLE;

---------------------------------------

CREATE TABLE TRANSACCIONES_PRESTAMOS
( ID_PRESTAMOS NUMBER,
  ID_OPERACION NUMBER,
  CONSTRAINT TRANSACCIONES_PRESTAMOS_PK PRIMARY KEY (ID_PRESTAMOS,ID_OPERACION));

ALTER TABLE TRANSACCIONES_PRESTAMOS
ADD CONSTRAINT fk_trasacciones_prestamos_a_prestamos
    FOREIGN KEY (ID_PRESTAMOS)
    REFERENCES PRESTAMOS(ID)
ENABLE;

ALTER TABLE TRANSACCIONES_PRESTAMOS
ADD CONSTRAINT fk_trasacciones_prestamos_operaciones_prestamos
    FOREIGN KEY (ID_OPERACION)
    REFERENCES OPERACIONES_PRESTAMOS(ID)
ENABLE;

----------------------------------


CREATE TABLE USUARIOS_CLIENTES
( ID NUMBER,
  LOGIN VARCHAR2(255 BYTE),
  PASSWORD_CLIENTE VARCHAR2(255 BYTE) NOT NULL,
  ID_CLIENTE NUMBER,
  CONSTRAINT USUARIOS_CLIENTES_PK PRIMARY KEY (ID));
  
ALTER TABLE USUARIOS_CLIENTES
ADD CONSTRAINT fk_usuarios_clientes_a_clientes
    FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTES(ID)
ENABLE;

----------------------------------------


CREATE TABLE CLIENTES
( ID NUMBER,
  NUMERO_DOCUMENTO NUMBER,
  TIPO VARCHAR2(255 BYTE) NOT NULL,
  TIPO_DOCUMENTO VARCHAR2(255 BYTE) NOT NULL,
  NOMBRE VARCHAR2(255 BYTE) NOT NULL,
  NACIONALIDAD VARCHAR2(255 BYTE) NOT NULL,
  DIRECCION_FISICA VARCHAR2(255 BYTE) NOT NULL,
  DIRECCION_ELECTRONICA VARCHAR2(255 BYTE) NOT NULL,
  TELEFONO VARCHAR2(255 BYTE) NOT NULL, 
  CODIGO_POSTAL VARCHAR2(255 BYTE) NOT NULL,
  CIUDAD VARCHAR2(255 BYTE) NOT NULL,
  DEPARTAMENTO VARCHAR2(255 BYTE) NOT NULL,
  CONSTRAINT CLIENTES_PK PRIMARY KEY (ID));

ALTER TABLE CLIENTES
	ADD CONSTRAINT CK_clientes_tipos
	CHECK (TIPO IN ('juridica','natural'))
ENABLE;

---------------------------------------

CREATE TABLE EMPLEADOS
( ID NUMBER,
  NUMERO_DOCUMENTO NUMBER,
  CARGO VARCHAR2(255 BYTE) NOT NULL,
  TIPO VARCHAR2(255 BYTE) NOT NULL,
  TIPO_DOCUMENTO VARCHAR2(255 BYTE) NOT NULL,
  NOMBRE VARCHAR2(255 BYTE) NOT NULL,
  NACIONALIDAD VARCHAR2(255 BYTE) NOT NULL,
  DIRECCION_FISICA VARCHAR2(255 BYTE) NOT NULL,
  DIRECCION_ELECTRONICA VARCHAR2(255 BYTE) NOT NULL,
  TELEFONO VARCHAR2(255 BYTE) NOT NULL, 
  CODIGO_POSTAL VARCHAR2(255 BYTE) NOT NULL,
  CIUDAD VARCHAR2(255 BYTE) NOT NULL,
  DEPARTAMENTO VARCHAR2(255 BYTE) NOT NULL,
  ID_OFICINA NUMBER NOT NULL,
  CONSTRAINT PERSONAS_PK PRIMARY KEY (ID));

ALTER TABLE EMPLEADOS
	ADD CONSTRAINT CK_TIPOS
	CHECK (TIPO IN ('juridica','natural'))
ENABLE;

ALTER TABLE EMPLEADOS
	ADD CONSTRAINT CK_CARGOS
	CHECK (CARGO IN ( 'Gerente general','Gerente oficina','Cajero'))
ENABLE;

ALTER TABLE EMPLEADOS
ADD CONSTRAINT fk_empleados_a_oficinas
    FOREIGN KEY (ID_OFICINA)
    REFERENCES OFICINAS(ID)
ENABLE;

---------------------------------------


CREATE TABLE USUARIOS_EMPLEADOS
( ID NUMBER,
  LOGIN VARCHAR2(255 BYTE),
  PASSWORD_EMPLEADOS VARCHAR2(255 BYTE) NOT NULL,
  ID_EMPLEADO NUMBER,
  CONSTRAINT USUARIOS_EMPLEADOS_PK PRIMARY KEY (ID));

ALTER TABLE USUARIOS_EMPLEADOS
ADD CONSTRAINT fk_empleados_a_oficinas
    FOREIGN KEY (ID_EMPLEADO)
    REFERENCES EMPLEADOS(ID)
ENABLE;

---------------------------------------
CREATE TABLE OFICINAS
( ID NUMBER,
  NOMBRE VARCHAR2(255 BYTE) NOT NULL,
  DIRECCION VARCHAR2(255 BYTE) NOT NULL,
  NUMERO_PUNTOS_ATENCION NUMBER  NOT NULL,
  GERENTE NUMBER NOT NULL,
  CIUDAD VARCHAR2(255 BYTE)  NOT NULL,
  CONSTRAINT OFICINAS_PK PRIMARY KEY (ID));
  
ALTER TABLE OFICINAS
ADD CONSTRAINT fk_oficinas_a_empleados
    FOREIGN KEY (GERENTE)
    REFERENCES GERENTES(ID)
ENABLE;
----------------------------------------

CREATE TABLE PUNTOS_ATENCION
( ID NUMBER,
  TIPO VARCHAR2(255 BYTE) NOT NULL,
  CIUDAD VARCHAR2(255 BYTE),
  HORARIO_ATENCION VARCHAR2(255 BYTE),
  DIRECCION VARCHAR2(255 BYTE),
  OFICINA NUMBER,
  CONSTRAINT PUNTOS_ATENCION_PK PRIMARY KEY (ID));
  
ALTER TABLE PUNTOS_ATENCION
	ADD CONSTRAINT CK_TIPOS
	CHECK (TIPO IN ('Perzonalizado','CajeroAutomatico','App','Web'))
ENABLE;

ALTER TABLE PUNTOS_ATENCION
ADD CONSTRAINT fk_puntos_atencion_oficinas
    FOREIGN KEY (OFICINA)
    REFERENCES OFICINAS(ID)
ENABLE;

----------------------------------------

CREATE TABLE OPERACIONES_PRESTAMOS
( ID NUMBER,
  TIPO_OPERACION VARCHAR2(255 BYTE) NOT NULL,
  FECHA DATE NOT NULL,
  CUENTA_PRESTAMO NUMBER,
  MONTO_OPERACION DECIMAL(10,2) NOT NULL,
  CLIENTE VARCHAR2(255 BYTE) NOT NULL,
  PUNTO_ATENCION NUMBER,
  CONSTRAINT OPERACIONES_PRESTAMOS_PK PRIMARY KEY (ID));

ALTER TABLE OPERACIONES_PRESTAMOS
ADD CONSTRAINT fk_op_prestamo_puntos_atencion
    FOREIGN KEY (PUNTO_ATENCION)
    REFERENCES PUNTOS_ATENCION(ID)
ENABLE;




  